# --- BACKGROUND MUSIC (BGM) ---
define audio.citynighthologram  = "assets/audio/scene 1-10/Scene 1 - City Night Sound.mp3"
define audio.office_ambience    = "assets/audio/scene 1-10/Scene 2 - Busy Office Ambience.mp3"
define audio.adrian_theme       = "assets/audio/scene 1-10/Scene 4 - Jazz Adrian Theme.mp3"
define audio.lonely_room        = "assets/audio/scene 1-10/Scene 5 - lonely_room.mp3"
define audio.menegangkan        = "assets/audio/scene 1-10/Scene 6 - backsound menegangkan.mp3"
define audio.mystery_low        = "assets/audio/scene 1-10/Scene 7 - mystery.mp3"
define audio.city_hum           = "assets/audio/scene 1-10/Scene 8 - city hum.mp3"
define audio.old_city_walk      = "assets/audio/scene 1-10/Scene 9 - old city walk.mp3"
define audio.public_ceremony    = "assets/audio/scene 1-10/Scene 10 - Public_ceremony.mp3"

define audio.quiet_alley        = "assets/audio/scene 1-10/quiet_alley.mp3"
define audio.workshop_warm      = "assets/audio/scene 1-10/workshop_warm.mp3"
define audio.debate_low         = "assets/audio/scene 1-10/debate_low.mp3"
define audio.soft_truth         = "assets/audio/scene 1-10/soft_truth.mp3"
define audio.cold_data          = "assets/audio/scene 1-10/cold_data.mp3"

# --- AMBIENT SOUNDS (LOOP) ---
define audio.rain               = "assets/audio/scene 1-10/Scene 7 - rain.mp3"
define audio.crowd_far          = "assets/audio/scene 1-10/Scene 10 - kerumunan bersorak.mp3"
define audio.city_noise_loud    = "assets/audio/scene 1-10/city_noise_loud.mp3"

# --- SOUND EFFECTS (SFX) ---
define audio.door_open          = "assets/audio/scene 1-10/Scene 3 - Door opening.mp3"
define audio.langkah_kaki       = "<from 0 to 5.0>assets/audio/scene 1-10/Scene 3 - Footstep.mp3"
define audio.box_open           = "assets/audio/scene 1-10/Scene 5 - Box_open.mp3"
define audio.device_ping        = "assets/audio/scene 1-10/Scene 6 & 8 - device_ping (notif).mp3"
define audio.confirm            = "assets/audio/scene 1-10/Scene 6 - confirm_task(edited).mp3"
define audio.metal_fix          = "<from 0 to 5.0>assets/audio/scene 1-10/Scene 7 - metal_fix.mp3"
define audio.device_glitch      = "assets/audio/scene 1-10/Scene 8 - device_glitch.mp3"
define audio.device_error_1     = "assets/audio/scene 1-10/Scene 8 - device_error(1).mp3"
define audio.device_error_2     = "assets/audio/scene 1-10/Scene 8 - device_error(2).mp3"
define audio.message_ping       = "assets/audio/scene 1-10/Scene 6 & 8 - device_ping (notif).mp3"
define audio.langkah_kaki_banyak = "assets/audio/scene 1-10/Scene 8 - langkah kaki banyak.mp3"
define audio.lift_sampai        = "assets/audio/scene 1-10/Scene 8 - lift sampai tujuan.mp3"
define audio.lift_tertutup      = "assets/audio/scene 1-10/Scene 8 - Pintu lift tertutup.mp3"
define audio.lift_terbuka       = "assets/audio/scene 1-10/Scene 8 - pintu otomatis terbuka.mp3" 
define audio.device_glitch_soft = "assets/audio/scene 1-10/Scene 10 - glitch soft.mp3"
define audio.crowd_cheer        = "assets/audio/scene 1-10/Scene 10 - kerumunan bersorak.mp3"
define audio.applause           = "assets/audio/scene 1-10/Scene 10 - tepuk tangan.mp3"
define audio.child_laugh_echo   = "assets/audio/scene 1-10/child_laugh_echo.mp3"


define audio.applause_loud      = "assets/audio/scene 1-10/applause_loud.mp3"

define audio.metal_tap          = "assets/audio/scene 1-10/metal_tap.mp3"
define audio.door_bell_old      = "assets/audio/scene 1-10/door_bell_old.mp3"
define audio.radio_static       = "assets/audio/scene 1-10/radio_static.mp3"
define audio.screwdriver_turn   = "assets/audio/scene 1-10/screwdriver_turn.mp3"
define audio.lamp_place_table   = "assets/audio/scene 1-10/lamp_place_table.mp3"
define audio.device_reboot      = "assets/audio/scene 1-10/device_reboot.mp3"
define audio.keyboard_click     = "assets/audio/scene 1-10/keyboard_click.mp3"